import { Anuncio_Tipo } from "./types";

export const articulos: Anuncio_Tipo[] = [
  {
    id: "1",
    title: "Título del objeto 1",
    description: "Descripción del objeto 1. Lorem ipsum dolor sit amet.",
    price: 238,
    anunciante: {
      name: "anunciante",
      email: "email@ejemplo.com",
      tlf: "123456789",
    },
    category: "213QY9n39zLmgMdsZrK1",
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    poster: "https://picsum.photos/200/150.webp",
    date: new Date("2024-06-20"),
    images: [
      "https://picsum.photos/600/400.webp?random=1",
      "https://picsum.photos/600/400.webp?random=2",
      "https://picsum.photos/600/400.webp?random=3",
      "https://picsum.photos/600/400.webp?random=4",
    ],
  },
  {
    id: "2",
    title: "Título del objeto 2",
    description: "Descripción del objeto 2. Lorem ipsum dolor sit amet.",
    price: 143,
    anunciante: {
      name: "anunciante",
      email: "email@ejemplo.com",
      tlf: "123456789",
    },
    category: "Hg48EUR9DIhSzB8APsgC",
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    poster: "https://picsum.photos/200/150.webp",
    date: new Date("2024-06-20"),
    images: [
      "https://picsum.photos/600/400.webp?random=1",
      "https://picsum.photos/600/400.webp?random=2",
      "https://picsum.photos/600/400.webp?random=3",
      "https://picsum.photos/600/400.webp?random=4",
    ],
  },
  {
    id: "3",
    title: "Título del objeto 3",
    description: "Descripción del objeto 3. Lorem ipsum dolor sit amet.",
    price: 372,
    anunciante: {
      name: "anunciante",
      email: "email@ejemplo.com",
      tlf: "123456789",
    },
    category: "anjcXQUFMGoI3T1zJVZn",
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    poster: "https://picsum.photos/200/150.webp",
    date: new Date("2024-06-20"),
    images: [
      "https://picsum.photos/600/400.webp?random=1",
      "https://picsum.photos/600/400.webp?random=2",
      "https://picsum.photos/600/400.webp?random=3",
      "https://picsum.photos/600/400.webp?random=4",
    ],
  },
  {
    id: "4",
    title: "Título del objeto 4",
    description: "Descripción del objeto 4. Lorem ipsum dolor sit amet.",
    price: 426,
    anunciante: {
      name: "anunciante",
      email: "email@ejemplo.com",
      tlf: "123456789",
    },
    category: "bfLahpjbX9V1rOOPFjyW",
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    poster: "https://picsum.photos/200/150.webp",
    date: new Date("2024-06-20"),
    images: [
      "https://picsum.photos/600/400.webp?random=1",
      "https://picsum.photos/600/400.webp?random=2",
      "https://picsum.photos/600/400.webp?random=3",
      "https://picsum.photos/600/400.webp?random=4",
    ],
  },
  {
    id: "5",
    title: "Título del objeto 5",
    description: "Descripción del objeto 5. Lorem ipsum dolor sit amet.",
    price: 87,
    anunciante: {
      name: "anunciante",
      email: "email@ejemplo.com",
      tlf: "123456789",
    },
    category: "ch86zNLs3kOeqLpZnDFB",
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    poster: "https://picsum.photos/200/150.webp",
    date: new Date("2024-06-20"),
    images: [
      "https://picsum.photos/600/400.webp?random=1",
      "https://picsum.photos/600/400.webp?random=2",
      "https://picsum.photos/600/400.webp?random=3",
      "https://picsum.photos/600/400.webp?random=4",
    ],
  },
  {
    id: "6",
    title: "Título del objeto 6",
    description: "Descripción del objeto 6. Lorem ipsum dolor sit amet.",
    price: 167,
    anunciante: {
      name: "anunciante",
      email: "email@ejemplo.com",
      tlf: "123456789",
    },
    category: "z8lgBcRvplCjoAYe7vF1",
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    poster: "https://picsum.photos/200/150.webp",
    date: new Date("2024-06-20"),
    images: [
      "https://picsum.photos/600/400.webp?random=1",
      "https://picsum.photos/600/400.webp?random=2",
      "https://picsum.photos/600/400.webp?random=3",
      "https://picsum.photos/600/400.webp?random=4",
    ],
  },
  {
    id: "7",
    title: "Título del objeto 7",
    description: "Descripción del objeto 7. Lorem ipsum dolor sit amet.",
    price: 285,
    anunciante: {
      name: "anunciante",
      email: "email@ejemplo.com",
      tlf: "123456789",
    },
    category: "213QY9n39zLmgMdsZrK1",
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    poster: "https://picsum.photos/200/150.webp",
    date: new Date("2024-06-20"),
    images: [
      "https://picsum.photos/600/400.webp?random=1",
      "https://picsum.photos/600/400.webp?random=2",
      "https://picsum.photos/600/400.webp?random=3",
      "https://picsum.photos/600/400.webp?random=4",
    ],
  },
  {
    id: "8",
    title: "Título del objeto 8",
    description: "Descripción del objeto 8. Lorem ipsum dolor sit amet.",
    price: 285,
    anunciante: {
      name: "anunciante",
      email: "email@ejemplo.com",
      tlf: "123456789",
    },
    category: "Hg48EUR9DIhSzB8APsgC",
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    poster: "https://picsum.photos/200/150.webp",
    date: new Date("2024-06-20"),
    images: [
      "https://picsum.photos/600/400.webp?random=1",
      "https://picsum.photos/600/400.webp?random=2",
      "https://picsum.photos/600/400.webp?random=3",
      "https://picsum.photos/600/400.webp?random=4",
    ],
  },
  {
    id: "9",
    title: "Título del objeto 9",
    description: "Descripción del objeto 9. Lorem ipsum dolor sit amet.",
    price: 307,
    anunciante: {
      name: "anunciante",
      email: "email@ejemplo.com",
      tlf: "123456789",
    },
    category: "anjcXQUFMGoI3T1zJVZn",
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    poster: "https://picsum.photos/200/150.webp",
    date: new Date("2024-06-20"),
    images: [
      "https://picsum.photos/600/400.webp?random=1",
      "https://picsum.photos/600/400.webp?random=2",
      "https://picsum.photos/600/400.webp?random=3",
      "https://picsum.photos/600/400.webp?random=4",
    ],
  },
  {
    id: "10",
    title: "Título del objeto 10",
    description: "Descripción del objeto 10. Lorem ipsum dolor sit amet.",
    price: 329,
    anunciante: {
      name: "anunciante",
      email: "email@ejemplo.com",
      tlf: "123456789",
    },

    category: "bfLahpjbX9V1rOOPFjyW",
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    poster: "https://picsum.photos/200/150.webp",
    date: new Date("2024-06-20"),
    images: [
      "https://picsum.photos/600/400.webp?random=1",
      "https://picsum.photos/600/400.webp?random=2",
      "https://picsum.photos/600/400.webp?random=3",
      "https://picsum.photos/600/400.webp?random=4",
    ],
  },
  {
    id: "11",
    title: "Título del objeto 11",
    description: "Descripción del objeto 11. Lorem ipsum dolor sit amet.",
    price: 437,
    anunciante: {
      name: "anunciante",
      email: "email@ejemplo.com",
      tlf: "123456789",
    },

    category: "ch86zNLs3kOeqLpZnDFB",
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    poster: "https://picsum.photos/200/150.webp",
    date: new Date("2024-06-20"),
    images: [
      "https://picsum.photos/600/400.webp?random=1",
      "https://picsum.photos/600/400.webp?random=2",
      "https://picsum.photos/600/400.webp?random=3",
      "https://picsum.photos/600/400.webp?random=4",
    ],
  },
  {
    id: "12",
    title: "Título del objeto 12",
    description: "Descripción del objeto 12. Lorem ipsum dolor sit amet.",
    price: 458,
    anunciante: {
      name: "anunciante",
      email: "email@ejemplo.com",
      tlf: "123456789",
    },

    category: "z8lgBcRvplCjoAYe7vF1",
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    poster: "https://picsum.photos/200/150.webp",
    date: new Date("2024-06-20"),
    images: [
      "https://picsum.photos/600/400.webp?random=1",
      "https://picsum.photos/600/400.webp?random=2",
      "https://picsum.photos/600/400.webp?random=3",
      "https://picsum.photos/600/400.webp?random=4",
    ],
  },
  {
    id: "13",
    title: "Título del objeto 13",
    description: "Descripción del objeto 13. Lorem ipsum dolor sit amet.",
    price: 329,
    anunciante: {
      name: "anunciante",
      email: "email@ejemplo.com",
      tlf: "123456789",
    },

    category: "213QY9n39zLmgMdsZrK1",
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    poster: "https://picsum.photos/200/150.webp",
    date: new Date("2024-06-20"),
    images: [
      "https://picsum.photos/600/400.webp?random=1",
      "https://picsum.photos/600/400.webp?random=2",
      "https://picsum.photos/600/400.webp?random=3",
      "https://picsum.photos/600/400.webp?random=4",
    ],
  },
  {
    id: "14",
    title: "Título del objeto 14",
    description: "Descripción del objeto 14. Lorem ipsum dolor sit amet.",
    price: 221,
    anunciante: {
      name: "anunciante",
      email: "email@ejemplo.com",
      tlf: "123456789",
    },

    category: "Hg48EUR9DIhSzB8APsgC",
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    poster: "https://picsum.photos/200/150.webp",
    date: new Date("2024-06-20"),
    images: [
      "https://picsum.photos/600/400.webp?random=1",
      "https://picsum.photos/600/400.webp?random=2",
      "https://picsum.photos/600/400.webp?random=3",
      "https://picsum.photos/600/400.webp?random=4",
    ],
  },
  {
    id: "15",
    title: "Título del objeto 15",
    description: "Descripción del objeto 15. Lorem ipsum dolor sit amet.",
    price: 449,
    anunciante: {
      name: "anunciante",
      email: "email@ejemplo.com",
      tlf: "123456789",
    },

    category: "anjcXQUFMGoI3T1zJVZn",
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    poster: "https://picsum.photos/200/150.webp",
    date: new Date("2024-06-20"),
    images: [
      "https://picsum.photos/600/400.webp?random=1",
      "https://picsum.photos/600/400.webp?random=2",
      "https://picsum.photos/600/400.webp?random=3",
      "https://picsum.photos/600/400.webp?random=4",
    ],
  },
  {
    id: "16",
    title: "Título del objeto 16",
    description: "Descripción del objeto 16. Lorem ipsum dolor sit amet.",
    price: 380,
    anunciante: {
      name: "anunciante",
      email: "email@ejemplo.com",
      tlf: "123456789",
    },

    category: "bfLahpjbX9V1rOOPFjyW",
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    poster: "https://picsum.photos/200/150.webp",
    date: new Date("2024-06-20"),
    images: [
      "https://picsum.photos/600/400.webp?random=1",
      "https://picsum.photos/600/400.webp?random=2",
      "https://picsum.photos/600/400.webp?random=3",
      "https://picsum.photos/600/400.webp?random=4",
    ],
  },
  {
    id: "17",
    title: "Título del objeto 17",
    description: "Descripción del objeto 17. Lorem ipsum dolor sit amet.",
    price: 430,
    anunciante: {
      name: "anunciante",
      email: "email@ejemplo.com",
      tlf: "123456789",
    },

    category: "ch86zNLs3kOeqLpZnDFB",
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    poster: "https://picsum.photos/200/150.webp",
    date: new Date("2024-06-20"),
    images: [
      "https://picsum.photos/600/400.webp?random=1",
      "https://picsum.photos/600/400.webp?random=2",
      "https://picsum.photos/600/400.webp?random=3",
      "https://picsum.photos/600/400.webp?random=4",
    ],
  },
  {
    id: "18",
    title: "Título del objeto 18",
    description: "Descripción del objeto 18. Lorem ipsum dolor sit amet.",
    price: 357,
    anunciante: {
      name: "anunciante",
      email: "email@ejemplo.com",
      tlf: "123456789",
    },

    category: "z8lgBcRvplCjoAYe7vF1",
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    poster: "https://picsum.photos/200/150.webp",
    date: new Date("2024-06-20"),
    images: [
      "https://picsum.photos/600/400.webp?random=1",
      "https://picsum.photos/600/400.webp?random=2",
      "https://picsum.photos/600/400.webp?random=3",
      "https://picsum.photos/600/400.webp?random=4",
    ],
  },
  {
    id: "19",
    title: "Título del objeto 19",
    description: "Descripción del objeto 19. Lorem ipsum dolor sit amet.",
    price: 375,
    anunciante: {
      name: "anunciante",
      email: "email@ejemplo.com",
      tlf: "123456789",
    },

    category: "213QY9n39zLmgMdsZrK1",
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    poster: "https://picsum.photos/200/150.webp",
    date: new Date("2024-06-20"),
    images: [
      "https://picsum.photos/600/400.webp?random=1",
      "https://picsum.photos/600/400.webp?random=2",
      "https://picsum.photos/600/400.webp?random=3",
      "https://picsum.photos/600/400.webp?random=4",
    ],
  },
  {
    id: "20",
    title: "Título del objeto 20",
    description: "Descripción del objeto 20. Lorem ipsum dolor sit amet.",
    price: 255,
    anunciante: {
      name: "anunciante",
      email: "email@ejemplo.com",
      tlf: "123456789",
    },

    category: "Hg48EUR9DIhSzB8APsgC",
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    poster: "https://picsum.photos/200/150.webp",
    date: new Date("2024-06-20"),
    images: [
      "https://picsum.photos/600/400.webp?random=1",
      "https://picsum.photos/600/400.webp?random=2",
      "https://picsum.photos/600/400.webp?random=3",
      "https://picsum.photos/600/400.webp?random=4",
    ],
  },
];
