import { Articulo_Tipo } from "./types";

export const articulos: Articulo_Tipo[] = [
  {
    id: "1",
    title: "Título del objeto 1",
    description: "Descripción del objeto 1. Lorem ipsum dolor sit amet.",
    price: 238,
    tlf: "123456789",
    email: "ejemplo1@mail.com",
    category: { id: "3", name: "Experiencias" },
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "https://picsum.photos/200/300?random=1",
    date: new Date("2024-06-20"),
  },
  {
    id: "2",
    title: "Título del objeto 2",
    description: "Descripción del objeto 2. Lorem ipsum dolor sit amet.",
    price: 143,
    tlf: "123456789",
    email: "ejemplo2@mail.com",
    category: { id: "5", name: "Deportes" },
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "https://picsum.photos/200/300?random=2",
    date: new Date("2024-06-20"),
  },
  {
    id: "3",
    title: "Título del objeto 3",
    description: "Descripción del objeto 3. Lorem ipsum dolor sit amet.",
    price: 372,
    tlf: "123456789",
    email: "ejemplo3@mail.com",
    category: { id: "6", name: "Gastronomía" },
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "https://picsum.photos/200/300?random=3",
    date: new Date("2024-06-20"),
  },
  {
    id: "4",
    title: "Título del objeto 4",
    description: "Descripción del objeto 4. Lorem ipsum dolor sit amet.",
    price: 426,
    tlf: "123456789",
    email: "ejemplo4@mail.com",
    category: { id: "1", name: "Artículos" },
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "https://picsum.photos/200/300?random=4",
    date: new Date("2024-06-20"),
  },
  {
    id: "5",
    title: "Título del objeto 5",
    description: "Descripción del objeto 5. Lorem ipsum dolor sit amet.",
    price: 87,
    tlf: "123456789",
    email: "ejemplo5@mail.com",
    category: { id: "5", name: "Deportes" },
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "https://picsum.photos/200/300?random=5",
    date: new Date("2024-06-20"),
  },
  {
    id: "6",
    title: "Título del objeto 6",
    description: "Descripción del objeto 6. Lorem ipsum dolor sit amet.",
    price: 167,
    tlf: "123456789",
    email: "ejemplo6@mail.com",
    category: { id: "3", name: "Experiencias" },
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "https://picsum.photos/200/300?random=6",
    date: new Date("2024-06-20"),
  },
  {
    id: "7",
    title: "Título del objeto 7",
    description: "Descripción del objeto 7. Lorem ipsum dolor sit amet.",
    price: 285,
    tlf: "123456789",
    email: "ejemplo7@mail.com",
    category: { id: "3", name: "Experiencias" },
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "https://picsum.photos/200/300?random=7",
    date: new Date("2024-06-20"),
  },
  {
    id: "8",
    title: "Título del objeto 8",
    description: "Descripción del objeto 8. Lorem ipsum dolor sit amet.",
    price: 285,
    tlf: "123456789",
    email: "ejemplo8@mail.com",
    category: { id: "6", name: "Gastronomía" },
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "https://picsum.photos/200/300?random=8",
    date: new Date("2024-06-20"),
  },
  {
    id: "9",
    title: "Título del objeto 9",
    description: "Descripción del objeto 9. Lorem ipsum dolor sit amet.",
    price: 307,
    tlf: "123456789",
    email: "ejemplo9@mail.com",
    category: { id: "4", name: "Entretenimiento" },
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "https://picsum.photos/200/300?random=9",
    date: new Date("2024-06-20"),
  },
  {
    id: "10",
    title: "Título del objeto 10",
    description: "Descripción del objeto 10. Lorem ipsum dolor sit amet.",
    price: 329,
    tlf: "123456789",
    email: "ejemplo10@mail.com",
    category: { id: "4", name: "Entretenimiento" },
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "https://picsum.photos/200/300?random=10",
    date: new Date("2024-06-20"),
  },
  {
    id: "11",
    title: "Título del objeto 11",
    description: "Descripción del objeto 11. Lorem ipsum dolor sit amet.",
    price: 437,
    tlf: "123456789",
    email: "ejemplo11@mail.com",
    category: { id: "6", name: "Gastronomía" },
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "https://picsum.photos/200/300?random=11",
    date: new Date("2024-06-20"),
  },
  {
    id: "12",
    title: "Título del objeto 12",
    description: "Descripción del objeto 12. Lorem ipsum dolor sit amet.",
    price: 329,
    tlf: "123456789",
    email: "ejemplo12@mail.com",
    category: { id: "1", name: "Artículos" },
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "https://picsum.photos/200/300?random=12",
    date: new Date("2024-06-20"),
  },
  {
    id: "13",
    title: "Título del objeto 13",
    description: "Descripción del objeto 13. Lorem ipsum dolor sit amet.",
    price: 405,
    tlf: "123456789",
    email: "ejemplo13@mail.com",
    category: { id: "3", name: "Experiencias" },
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "https://picsum.photos/200/300?random=13",
    date: new Date("2024-06-20"),
  },
  {
    id: "14",
    title: "Título del objeto 14",
    description: "Descripción del objeto 14. Lorem ipsum dolor sit amet.",
    price: 374,
    tlf: "123456789",
    email: "ejemplo14@mail.com",
    category: { id: "5", name: "Deportes" },
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "https://picsum.photos/200/300?random=14",
    date: new Date("2024-06-20"),
  },
  {
    id: "15",
    title: "Título del objeto 15",
    description: "Descripción del objeto 15. Lorem ipsum dolor sit amet.",
    price: 488,
    tlf: "123456789",
    email: "ejemplo15@mail.com",
    category: { id: "6", name: "Gastronomía" },
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "https://picsum.photos/200/300?random=15",
    date: new Date("2024-06-20"),
  },
  {
    id: "16",
    title: "Título del objeto 16",
    description: "Descripción del objeto 16. Lorem ipsum dolor sit amet.",
    price: 297,
    tlf: "123456789",
    email: "ejemplo16@mail.com",
    category: { id: "3", name: "Experiencias" },
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "https://picsum.photos/200/300?random=16",
    date: new Date("2024-06-20"),
  },
  {
    id: "17",
    title: "Título del objeto 17",
    description: "Descripción del objeto 17. Lorem ipsum dolor sit amet.",
    price: 337,
    tlf: "123456789",
    email: "ejemplo17@mail.com",
    category: { id: "5", name: "Deportes" },
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "https://picsum.photos/200/300?random=17",
    date: new Date("2024-06-20"),
  },
  {
    id: "18",
    title: "Título del objeto 18",
    description: "Descripción del objeto 18. Lorem ipsum dolor sit amet.",
    price: 337,
    tlf: "123456789",
    email: "ejemplo18@mail.com",
    category: { id: "1", name: "Artículos" },
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "https://picsum.photos/200/300?random=18",
    date: new Date("2024-06-20"),
  },
  {
    id: "19",
    title: "Título del objeto 19",
    description: "Descripción del objeto 19. Lorem ipsum dolor sit amet.",
    price: 329,
    tlf: "123456789",
    email: "ejemplo19@mail.com",
    category: { id: "4", name: "Entretenimiento" },
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "https://picsum.photos/200/300?random=19",
    date: new Date("2024-06-20"),
  },
  {
    id: "20",
    title: "Título del objeto 20",
    description: "Descripción del objeto 20. Lorem ipsum dolor sit amet.",
    price: 354,
    tlf: "123456789",
    email: "ejemplo20@mail.com",
    category: { id: "3", name: "Experiencias" },
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "https://picsum.photos/200/300?random=20",
    date: new Date("2024-06-20"),
  },
  {
    id: "21",
    title: "Título del objeto 21",
    description: "Descripción del objeto 21. Lorem ipsum dolor sit amet.",
    price: 495,
    tlf: "123456789",
    email: "ejemplo21@mail.com",
    category: { id: "4", name: "Entretenimiento" },
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "https://picsum.photos/200/300?random=21",
    date: new Date("2024-06-20"),
  },
  {
    id: "22",
    title: "Título del objeto 22",
    description: "Descripción del objeto 22. Lorem ipsum dolor sit amet.",
    price: 253,
    tlf: "123456789",
    email: "ejemplo22@mail.com",
    category: { id: "2", name: "Servicios" },
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "https://picsum.photos/200/300?random=22",
    date: new Date("2024-06-20"),
  },
  {
    id: "23",
    title: "Título del objeto 23",
    description: "Descripción del objeto 23. Lorem ipsum dolor sit amet.",
    price: 176,
    tlf: "123456789",
    email: "ejemplo23@mail.com",
    category: { id: "5", name: "Deportes" },
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "https://picsum.photos/200/300?random=23",
    date: new Date("2024-06-20"),
  },
  {
    id: "24",
    title: "Título del objeto 24",
    description: "Descripción del objeto 24. Lorem ipsum dolor sit amet.",
    price: 275,
    tlf: "123456789",
    email: "ejemplo24@mail.com",
    category: { id: "6", name: "Gastronomía" },
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "https://picsum.photos/200/300?random=24",
    date: new Date("2024-06-20"),
  },
  {
    id: "25",
    title: "Título del objeto 25",
    description: "Descripción del objeto 25. Lorem ipsum dolor sit amet.",
    price: 473,
    tlf: "123456789",
    email: "ejemplo25@mail.com",
    category: { id: "1", name: "Artículos" },
    details: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "https://picsum.photos/200/300?random=25",
    date: new Date("2024-06-20"),
  },
];
